language: python

# 3.5-dev because of http://bugs.python.org/issue25131
matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.7.4
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38
    # - python: 3.9
    #   env: TOXENV=py39
    # - python: pypy
    #   env: TOXENV=pypy
before_install:
  - python --version
  - uname -a
  - lsb_release -a
  - sudo apt-get -qq update
  - sudo apt-get install -y enchant
install:
  - pip install -U setuptools
  - pip install tox coverage coveralls
  - pip install -r requirements.txt
  - virtualenv --version
  - easy_install --version
  - pip --version
  - tox --version
  - coverage --version
script:
    # Test install with current version of setuptools
  - pip install .
  # - tox -e coverage-erase,$TOXENV
  - tox -e $TOXENV
after_success:
  - tox -e coveralls
after_failure:
  - more .tox/log/* | cat
  - more .tox/*/log/* | cat
notifications:
  email:
    on_success: always
    on_failure: always
deploy:
  provider: pypi
  user: mambix
  password:
    secure: "SnSEZJK9zI0EQMLb6N3cAyw7c9Clr4j2xmFioRay/U8ggJrf3vMvgbUKEhDfPtCZDwQjPYig5Nlez3Ays72Qv30RISG1NCBuoRLvAE99GP6d9+MIR4+t1Gli6ckLsQOwvfgtsGGyI/IZLggX0zuuHr29To5T8YQi5TwB/krz4ro="
  on:
    branch: master
    tags: true
