language: python
matrix:
  include:
  - python: 3.6
    env: TOXENV=py36
  - python: 3.7
    env: TOXENV=py37
  - python: 3.7.4
    env: TOXENV=py37
  - python: 3.8
    env: TOXENV=py38
before_install:
- python --version
- uname -a
- lsb_release -a
- sudo apt-get -qq update
- sudo apt-get install -y enchant
install:
- pip install -U setuptools
- pip install tox coverage coveralls
- pip install -r requirements.txt
- virtualenv --version
- easy_install --version
- pip --version
- tox --version
- coverage --version
script:
- pip install .
- tox -e $TOXENV
after_success:
- tox -e coveralls
after_failure:
- more .tox/log/* | cat
- more .tox/*/log/* | cat
notifications:
  email:
    on_success: always
    on_failure: always
deploy:
  provider: pypi
  twine_version: 2.0.0
  username: __token__
  password:
    secure: dc5VVxJpSjuhkN31fOqEv62a8FbLIQNdEdDfopTjShpab9mAiRrSt+dYrwx81w9j9bgTWCR0SbLlIrC4NyqAjkEoQPDQMpt2EJfU6iLVxdQHYS41Shy+4OT/xfWjgaEa32JSwV7cvq8EO/CVHgnnwy3DyQnrG/8WyU5RejAX+EXW2mCYrJxGYryburVx4z+TO2gtiODbeoWSfjf+0+smPz9pNrnDgAPotQbW23FTvRoX+p8HKgyy8T38jTF3kgEuuen44ntWecTPmsFkP9MrpUmkBspRgPtfjq0GlbcYp56NGeqG8BbS2LSin9VkAxl89tVOgXexg6N+WlS0TOmEtytjgoiuZGgcxpf7cKrLjA/q7OWrSAQGHSSmAy919Ku6Hvc3bB7TYYxW4a+IKiSSrxT7I2qaGKCm7DUJDiKmZIdK9AoxVzm6Ps1cKDTPLvwlQztm7rXGsySo7vfoiDhgipxhbDBu7aDLt8vRb9rlpd1gC0jTqeL1OtCx4ZBNLXl0xI6++7etsXgymG98GlYVsiyeHJYxFBGRCO7VzqG4UWgGP8WCAjKQxPuIePET7vgsRyLQO2ALdemgJ3P9ozW8muaOaayvoyqSxAdCvmPVDKh90E74GdLMLICqPtnI4V50gjLnyuhBQE4BS6ymDSFFXviTNFuSHOkMjGNZiOR3Wcg=
  skip_existing: true
  on:
    branch: master
    tags: true
